backpanel/urls.py
from django.urls import path
from .views import *

app_name = 'backpanel'

urlpatterns = [
    path('', backpanel_home, name='backpanel_home'),
    path('compute', run_computation, name='computation')
]

dashbuilder/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('frontpanel', include('frontpanel.urls', namespace='front')),
    path('backpanel/', include('backpanel.urls', namespace='back')),
]

frontpanel/urls.py
from django.urls import path
from .views import *

app_name = 'frontpanel'

urlpatterns = [
    path('', frontpanel_home, name='frontpanel_home')
]

backpanel/models.py
from django.db import models

# Create your models here.

frontpanel/models.py
from django.db import models

# Create your models here.

backpanel/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from ast import literal_eval


def backpanel_home(request):
    if request.method == 'GET':
        return render(request, 'backpanel.html')


@csrf_exempt
def run_computation(request):
    if request.method == 'POST':
        body = literal_eval(request.body.decode('utf-8'))
        return JsonResponse(eval(body.get('data')), safe=False)

dashbuilder/views.py
from django.shortcuts import render


def home(request):
    if request.method == 'GET':
        return render(request, 'index.html')

frontpanel/views.py
from django.shortcuts import render


def frontpanel_home(request):
    if request.method == 'GET':
        return render(request, 'frontpanel.html')

templates/backpanel.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Back Panel Logic Diagram</title>
  </head>
  <body onload="backPanelDataLoading();">

    <br>

    <div class="container">
        <div class="row" style="width: 50%; margin-left: auto; margin-right: auto;">
            <div id="slider" class="col-sm-12 text-center" style="margin-top: 30px; margin-bottom: 80px;">
                <input id="slider_diagram" type="text" class="form-control" placeholder="slider value" style="height: 5em; width: 15em; margin-right: auto; margin-left: auto;" disabled>
            </div>
            <div id="python_code" class="col-sm-12" style="margin-bottom: 80px;">
                <input id="python_code_value" type="text" class="form-control" placeholder="Enter python code" style="height: 8em;">
            </div>
            <div id="textfield" class="col-sm-12">
                <input type="text" class="form-control" placeholder="TextField" disabled style="height: 5em; width: 15em; margin-right: auto; margin-left: auto; margin-bottom: 20px;">
            </div>
            <div id="connect_block_btn" class="col-sm-12 text-center">
                <button type="button" class="btn btn-primary" onclick="connectLines();">Connect Blocks</button>
            </div>
        </div>
    </div>    

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'js/leader-line.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}
  </body>
</html>

templates/frontpanel.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Front Panel Logic Building
{% endblock %}

{% block content %}

    <br>
    <div class="row">
        <div class="col-md-12 text-center">
            <button type="button" class="btn btn-success btn-lg" onclick="run();">Run</button>
        </div>
    </div>

    <br><br>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4" style="border: 1px solid black;">
                <div class="row">
                    <!-- <div class="col-sm-12 text-center">
                        <h2>Inputs</h2>
                    </div> -->
                    <div class="col-sm-12" style="cursor: pointer;padding: 10px 50px;">
                        <img src="{% static 'img/slider.png' %}" alt="slider image" id="slider_image"  title="slider" draggable="true" ondragstart="sliderDragStart(event);">
                    </div>
                    <!-- <div class="col-sm-12 text-center">
                        <h2>Outputs</h2>
                    </div> -->
                    <div class="col-sm-12" style="cursor: pointer;padding: 10px 50px;">
                        <img src="{% static 'img/textfield.png' %}" alt="textfield image" id="textfield_image" title="textfield" draggable="true" ondragstart="textFieldDragStart(event);">
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div id="slider_area" class="col-sm-12 text-center font-weight-bold" style="padding: 80px 60px;height: 200px;" ondragenter="sliderEntersInDropZone(event);" ondragover="sliderDragOverDropZone(event);" ondragleave="sliderLeavesDropZone(event);" ondrop="sliderDropsInDropZone(event);">
                        Drag the Slider here
                    </div>
                    <div id="textfield_area" class="col-sm-12 text-center font-weight-bold" style="padding: 80px 60px;height: 200px;" ondragenter="textFieldEntersInDropZone(event);" ondragover="textFieldDragOverDropZone(event);" ondragleave="textFieldLeavesDropZone(event);" ondrop="textFieldDropsInDropZone(event);">                        
                        Drag the TextField here
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br>

    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 text-right">
            <button class="btn btn-primary btn-lg" onclick="openBackPanel();">Backpanel</button>
          </div>
        </div>
    </div>
  
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
        <h1 class="display-4">Dash Builder</h1>
        <p class="lead">Labview Alternative</p>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body text-center">
                  <!-- <h5 class="card-title">Front Panel</h5> -->
                  <a href="{% url 'front:frontpanel_home' %}" class="btn btn-primary btn-lg">Front Panel</a>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body text-center">
                  <!-- <h5 class="card-title">Back Panel</h5> -->
                  <a href="{% url 'back:backpanel_home' %}" class="btn btn-primary btn-lg">Back Panel</a>
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock %}